name: MacOS (build-&-test)

on:
  push:
    branches: 
      - master 
      - devel
  pull_request:
    branches: 
      - master 
      - devel

jobs:
  setup:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Building MacOS dependencies
        run: brew install spot
      - name: Compile
        run: make release
      - name: Test the library
        run: make test
